# render.yaml — SmartBiz Backend (FastAPI on Render)

databases:
  - name: smartbiz-db-01
    plan: free
    databaseName: smartbiz_db_rcfg
    user: smartbiz_db_rcfg_user
    region: oregon

services:
  - type: web
    name: smartbiz-backend
    env: python
    plan: free
    region: oregon
    autoDeploy: true
    rootDir: .
    pythonVersion: 3.11

    buildCommand: |
      set -e
      python -m pip install --upgrade pip
      # Soma requirements kwenye ROOT (rahisisha)
      pip install --no-cache-dir -r requirements.txt
      python -m compileall backend

    startCommand: >
      uvicorn backend.main:app
      --host 0.0.0.0 --port $PORT
      --proxy-headers --forwarded-allow-ips="*"
      --log-level info
      --workers 1

    healthCheckPath: /health
    healthCheckTimeout: 10
    healthCheckInterval: 15

    envVars:
      # ---- Python/Runtime ----
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"

      # ---- DB (auto from database resource) ----
      - key: DATABASE_URL
        fromDatabase:
          name: smartbiz-db-01
          property: connectionString

      # ---- App env ----
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "false"
      - key: AUTO_CREATE_TABLES
        value: "true"   # zima ukitegemea Alembic pekee

      # ---- Security / JWT ----
      - key: JWT_SECRET
        sync: false        # weka value kupitia UI (dashboard)

      # ---- CORS ----
      - key: ALLOW_ORIGINS
        value: "https://smartbizsite.netlify.app,https://smartbiz.site,https://www.smartbiz.site,http://localhost:5173"
      - key: ALLOW_CREDENTIALS
        value: "true"

      # ---- URLs ----
      - key: NETLIFY_PUBLIC_URL
        value: https://smartbizsite.netlify.app
      - key: BACKEND_PUBLIC_URL
        value: https://smartbiz-backend-<slug>.onrender.com

      # ---- Locale/Time ----
      - key: TZ
        value: Africa/Dar_es_Salaam
