from backend.schemas.user import UserOut
"""Add connected_platforms table

Revision ID: 080de68b8570
Revises: 748eaac09146
Create Date: 2025-04-17 06:48:32.671385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '080de68b8570'
down_revision: Union[str, None] = '748eaac09146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_logs', sa.Column('sender', sa.String(), nullable=True))
    op.add_column('message_logs', sa.Column('username', sa.String(), nullable=True))
    op.add_column('message_logs', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('message_logs', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.alter_column('message_logs', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('message_logs', 'message_text')
    op.drop_column('message_logs', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_logs', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('message_logs', sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('message_logs', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('message_logs', 'received_at')
    op.drop_column('message_logs', 'message')
    op.drop_column('message_logs', 'username')
    op.drop_column('message_logs', 'sender')
    # ### end Alembic commands ###

